//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        arbiter_cpu_regs_defines.v
//
//  Module:
//        arbiter_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by the University of Cambridge Computer Laboratory 
// under EPSRC INTERNET Project EP/H040536/1, National Science Foundation under Grant No. CNS-0855268,
// and Defense Advanced Research Projects Agency (DARPA) and Air Force Research Laboratory (AFRL),
// under contract FA8750-11-C-0249.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA Open Systems C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.<future link here>
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


           `define  REG_RO_BITS				31:0
           `define  REG_RO_WIDTH				32
           `define  REG_RO_DEFAULT			32'h000000ab
           `define  REG_RO_ADDR				32'h0
           

           `define  REG_WO_BITS				31:0
           `define  REG_WO_WIDTH				32
           `define  REG_WO_DEFAULT			32'h1
           `define  REG_WO_ADDR				32'h4
           

           `define  REG_WOE_BITS				31:0
           `define  REG_WOE_WIDTH				32
           `define  REG_WOE_DEFAULT			32'h0
           `define  REG_WOE_ADDR				32'h8
           

           `define  REG_ROC_BITS				31:0
           `define  REG_ROC_WIDTH				32
           `define  REG_ROC_DEFAULT			32'h0
           `define  REG_ROC_ADDR				32'hC
           

           `define  REG_RWS_BITS				31:0
           `define  REG_RWS_WIDTH				32
           `define  REG_RWS_DEFAULT			32'h0
           `define  REG_RWS_ADDR				32'h10
           

           `define  REG_RWCR_BITS				31:0
           `define  REG_RWCR_WIDTH				32
           `define  REG_RWCR_DEFAULT			31'h0
           `define  REG_RWCR_ADDR				32'h14
           

           `define  REG_RWCW_BITS				31:0
           `define  REG_RWCW_WIDTH				32
           `define  REG_RWCW_DEFAULT			31'h0
           `define  REG_RWCW_ADDR				32'h18
           

           `define  REG_RWA_BITS				31:0
           `define  REG_RWA_WIDTH				32
           `define  REG_RWA_DEFAULT			32'h0
           `define  REG_RWA_ADDR				32'h1C
           
